# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "terragrunt-blek-terraform-state-non-prod-us-east-1"
    dynamodb_table = "terraform-locks"
    encrypt        = true
    key            = "non-prod/us-east-1/stage/webserver-cluster/terraform.tfstate"
    profile        = "non-prod"
    region         = "us-east-1"
  }
}
